name: alpha
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable:
  flutter_secure_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker:  
  get:
  mocktail:
  test:

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/flags/
    - assets/images/icons/

  fonts:
    - family: OperatorMonoLig
      fonts:
        - asset: assets/fonts/OperatorMonoLig-Book.otf
